### ISSUE TITLE
ready to release?

### ISSUE THREAD

**Issue by dboas** [fNIRS/snirf#10]
@fangq and @jayd1860 , what more is needed to be completed to release the spec?
Maybe all the issues except for the streaming one?
Should we invite all the supporters to this project and give them a little more time to comment?
Anything else?
@dboas

**Comment by fangq** [comment]
hi David, we haven't announced this repository yet, we should get more feedback. but feature wise, I think it looks quite good.

**Comment by jayd1860** [comment]
David and Qianqian, 

Had a question about the stim structure. We now have 

   stim(n).name
   stim(n).data

stim(n).data is a 3 column array where each row corresponds to a stimulus trial and the three columns indicate [starttime duration value].

In Homer2, users can manually reject/toggle stims and we indicate this with various non-zero and non-one values. Assuming we want to preserve this functionality in SNIRF and Homer3, do we use the last column for this purpose? 

I didn't see any description in the Spec about the last column. Should we add a short description of it's use?

**Comment by dboas** [comment]
Qianqian, should I go ahead and announce it? To announce it, should I email the small group of people and tell them to come to GitHub at https://github.com/fNIRS/snirf/ ? I would email them at snirf at fnirs.irg

Jay, I moved your comment to a new issue.

**Comment by fangq** [comment]
let's finish a few changes first: 1) add the contributor list, 2) add streaming support (pull #11), and I will move landmark/landmarkName to sd. 

after that, I will create a RFC commit and update the README, then we can invite people to comment on a clean version.

**Comment by fangq** [comment]
one more minor change before release - I would also remove the [two lines ](https://github.com/fNIRS/snirf/commit/06e210379876e797098057ae35c373323c05b754#diff-ee33e2b4d0875712a7909355275c703aR5) regarding the "last update dates", since now it is version controlled by git.

**Comment by fangq** [comment]
@dboas and @jayd1860, I created a [clean copy of the specification](https://github.com/fNIRS/snirf/commit/88baa2a2ed3347e868ec184b9daa4b357ddbbfd1), should be ready for user comments.

do you want to announce it to the mailing list?

**Comment by dboas** [comment]
Yeah, I will mention it to the mail list.
Thanks Qianqian!
David
