### ISSUE TITLE
Release version 1.1.0

### ISSUE THREAD

**Issue by rob-luke** [fNIRS/snirf#100]
Once the following issues are resolved I suggest we release a new version `1.1.0`:

* #89 
* #98 

In addition to the issues above, here is the changelog since version 1.0:

* Add dataUnit to indexed groups aux and measurementList
* Uses of the word "numerical" were replaced with "numeric" for consistency.
* stim/data was incorrectly described as `[<f>,...]+` in the table when it should be `[[<f>,...]]+`
* aux/dataTimeSeries was incorrectly described as `[[<f>,...]]+` in the table when it should be `[<f>,...]+`
* aux/dataTimeSeries and aux/time were described as `numeric` in the document when they should be `1-D numeric array`
* probe/detectorPos2D was described as `numeric` in the document when it should be `2-D array`

Additionally, we now have the wonderful validator, so that's great too.

Thoughts @sstucker @dboas ?

**Comment by sstucker** [comment]
Sounds good! I'll have #99 merged by your tomorrow :)

**Comment by rob-luke** [comment]
No rush! 2 minutes was a faster turn around than I was expecting 😉

**Comment by sstucker** [comment]
Okay! We just bit the bullet on lots of changes! 

Let's let the dust settle for a bit. I'll generate and test some code based on the new spec and make sure we're not missing something.

**Comment by rob-luke** [comment]
Probably worth ticking off #81 if we can too. I agree to waiting a bit for us to test it before releasing.

**Comment by sstucker** [comment]
By merging #86 ?

**Comment by rob-luke** [comment]
> By merging #86 ?

I think it still needs some work, I might get a chance to look at it later this week.
