### ISSUE TITLE
Source power unit inconsistency

### ISSUE THREAD

**Issue by samuelpowell** [fNIRS/snirf#104]
Note that the current and draft specification states:

> #### /nirs(i)/data(j)/measurementList(k)/sourcePower 
> * **Presence**: optional
> * **Type**:  numeric
> * **Location**: `/nirs(i)/data(j)/measurementList(k)/sourcePower`
> 
> Source power in milliwatt (mW). 

But later in the discussion it is noted that:

> `sourcePower` provides the option for information about the source power for that channel to be saved along with the data. The units are not defined, unless the user takes the option of using a `metaDataTag` described below to define, for instance, `sourcePowerUnit`

For our purposes we would prefer to be able to specify a unit (since our power measures are relative), but in any case one of the statements should be altered for clarity.

**Comment by dboas** [comment]
I agree that the inconsistency should be resolved. Keeping the latter seems more general. 

The proposal is thus to change the former to match the latter.

Perhaps this is best done by replacing

> Source power in milliwatt (mW).

with 

> The units are not defined, unless the user takes the option of using a `metaDataTag` as described below 

Thoughts?

**Comment by samuelpowell** [comment]
LGTM, happy to open a PR if this is not contentious.
