### ISSUE TITLE
Local to global indexing

### ISSUE THREAD

**Issue by samuelpowell** [fNIRS/snirf#106]
If we use local indexing, that is to say that:

 - for each channel we set a `sourceModuleIndex`, and a `detectorModuleIndex`, and use local indices for `sourceIndex` and `detectorIndex`
 - we set `useLocalIndex` non-zero             

Is the nature of the global indexing into, e.g., `/nirs(i)/probe/sourcePos3D` defined by specification?

**Comment by nidadu** [comment]
@samuelpowell I would think that's correct from the description here: https://github.com/fNIRS/snirf/blob/master/snirf_specification.md#nirsiprobeuselocalindex

**Comment by samuelpowell** [comment]
In which case the indexing is undefined and thus there cannot be a valid implementation that uses local indexing.  Whilst problematic (!) this does mean that we are able to add such a specification as a non-breaking change.

**Comment by samuelpowell** [comment]
Thanks @fangq. I suspect option (1) might be the most prudent. An alternative would be to enforce a global indexing scheme, but allow the module fields to be used to record the logical layout of the system.

Since practical use of the data eventually requires a flat / global representation (even if only implicit) I am tempted by the latter. We can discuss this on the next call @rob-luke .

(As an aside, I appreciate your motivation here; at the firmware level, Gowerlabs' LUMO operates in a manner similar to that which you describe. It's all very elegant, but in practice we maintain an associated mapping to a global / flat representation at a very low level of the software stack, and I suspect most people would do the same in a practical implementation).

**Comment by samuelpowell** [comment]
Following discussion in May 24 meeting I propose that we remove the use of local indexing for the purposes of enumerating channels. Instead, we enforce that a global representation is always defined.

To begin, we remove the field `/nirs(i)/probe/useLocalIndex` from the specification.

It is accepted that we may still wish to convey a description of the modular layout of the system.
 
Option 1:

 - Retain the `sourceModuleIndex` and `detectorModuleIndex` optional fields
 - Add optional fields `sourceLocalIndex` and `detectorLocalIndex` to complete the description of a modular system

Option 2:

 - Remove the `sourceModuleIndex` and `detectorModuleIndex` optional fields, and allow manufacturers to use the source and detector labels to convey information about the modular configuration of the system, which can be parsed if required.

**Comment by Horschig** [comment]
Option 2 is a bit hacky, but since we do not only have to make a specification but also make it usable for others to work with, it is the easier option (especially when it comes to supporting the spec in toolboxes like Homer). I would prefer option 1, but pragmatically it feels to me like option 2 is the way to go (at least for now).

**Comment by samuelpowell** [comment]
@Horschig noted, thank you. And of course nothing prevents us from doing (2) now and (1) later. Will await some more feedback before considering a PR to this effect.

**Comment by samuelpowell** [comment]
In call of 10/07 it was agreed to take option (2). More generally, the details of acquisiton (insofar as this relates to the data) might be considered further in the future, but a proper design is required.
