### ISSUE TITLE
Aux time series dimensionality limit

### ISSUE THREAD

**Issue by samuelpowell** [fNIRS/snirf#107]
We are examining how best to 'fit' auxiliary data from [LUMO ](https://www.gowerlabs.co.uk/lumo) into a valid SNIRF file, pertinent examples of which are:
1. Up to 54 individual time series of 6- or 9-axis MPU data at 100Hz 
2. Per-channel time series data metrics/flags, such as coupling quality

The most natural way for us to achieve this would be to write these data in the `/aux` group, which I note (from #86) is intended for the storage of arbitrary time series data. As specified, the auxiliary time series are limited to being vectors:

> **/nirs(i)/aux(j)/dataTimeSeries**
>  - **Presence**: optional; required if aux is used
>  - **Type**: numeric 1-D array
>  - **Location**: /nirs(i)/aux(j)/dataTimeSeries

If we are limited to a vector, the former example could require up to 486 auxiliary time series, and the latter two orders of magnitude more!

Might it be possible to extend the specification to permit (manufacturer specific) auxiliary data to be a matrix?

**Comment by sstucker** [comment]
Including this in the overhaul I am working on re: #103

**Comment by samuelpowell** [comment]
Thanks @sstucker
