### ISSUE TITLE
Converting NIRO-200NX data to snirf

### ISSUE THREAD

**Issue by JonteP** [fNIRS/snirf#125]
I posed this question at Neurostars (https://neurostars.org/t/convert-to-snirf-format/24855) and was recommended to post an issue here as well. I copy my question here:

>  am looking into BIDS formatting our fNIRS data. We have used a more clinically oriented device, NIRO-200NX, which provides the following measurements:
Tissue oxygenation index, TOI (%)
Normalized tissue hemoglobin index, nTHI (absolute value in arbitrary unit)
Oxygenated hemoglobin change, ∆O2Hb (μmol/L)
Deoxygenated hemoglobin change, ∆HHb (μmol/L)
Total hemoglobin change, ∆cHb (μmol/L)
>
> Looking at the format spec of Snirf, I cannot find any correspondence among dataTypeLabels to the first two (TOI and nTHI). Am I missing something or are they simply outside of the scope of the format?

A related question:
We recorded the 3d coordinates of the optode placements in subject space using neuronavigation equipment + a t1w image. I define this space as 'individual' now, but how do I link this to the t1 image used?

**Comment by samuelpowell** [comment]
In a meeting of 17/04/2024 
 - it was agreed that StO2 should be added to list of valid entries in the `dataTypeLabel` field
 - it is acceptable and intended that _changes_ in HbO, HbR, and HbT be stored using the associated `dataTypeLabel` despite the lack of the delta annotation (see #126 for a proposal about absolute values)
 - more obscure values such as nTHI might best be stored in an auxiliary field, @Horschig to provide further details.
 
 The latter question is outside of the scope of the SNIRF specification.
