### ISSUE TITLE
sd.landmarkLabels for sources and detectors

### ISSUE THREAD

**Issue by dboas** [fNIRS/snirf#15]
Qianqian, sd.landmarkLabels allows for user defined landmark labels. Should we provide a specification for what labels to use to reference specific sources and detectors?
We already have sd.srcLabels and sd.detLabels. We could just indicate that the sd.landmakrLabels should match the src or det label.
What do you think?
If you agree, can you add that to the spec?

**Comment by fangq** [comment]
sure. do you see a good chance that src/det may have overlapping labels? for example, could it be possible (or even frequently seen) that src channels are labeled as "1", "2" and "3" while the detectors labels may also follow the same format? 

in this case, I would suggest to add a prefix, such as "S:channel_1" for source label "channel_1" and "D:2" refers to detector label "2".

if we don't want to be too restrictive, we can just ask users to define unique src/det/landmark labels (i.e. srcLabels, detLabels and the non-optode landmark names in the landmarkLabels should be unique).

what do you think?

**Comment by fangq** [comment]
let me know if this works

https://github.com/fNIRS/snirf/pull/18
