### ISSUE TITLE
[Inconsistency] dataOffset vs  offset

### ISSUE THREAD

**Issue by Edouard2laire** [fNIRS/snirf#161]
Hello, 

**Describe the inconsistency**

The standard is definining /nirs(i)/data(j)/dataOffset (https://github.com/fNIRS/snirf/blob/master/snirf_specification.md#nirsidatajdataoffset)  as a numeric 1-D array containing one offset per channel that should be added to dataTimeSeries.

However,  the summary https://github.com/fNIRS/snirf/blob/master/snirf_specification.md#snirf-data-format-summary 
mention only the field 'offset' which is an absolute offset for all the channels. 

From this, it seems it is possible to have two offsets: 
-  /nirs(i)/data(j)/dataOffset: numeric 1-D array with one offset per channel
- /nirs(i)/data(j)/Offset : numeric with one global offset (same for all the channels)

**Current specification**
-  /nirs(i)/data(j)/dataOffset: 

> Presence: optional
> Type: numeric 1-D array
> Location: /nirs(i)/data(j)/dataOffset
> This stores an optional offset value per channel, which, when added to /nirs(i)/data(j)/dataTimeSeries, results in absolute data values.
> 
> The length of this array is equal to the as represented by the second dimension in the dataTimeSeries.

-   /nirs(i)/data(j)/Offset: 

> SNIRF-formatted NIRS data structure / Meaning of the data / Type
> offset / * Absolute offset for all channels /   [<f>,...] *

**Corrected specification**

There are two solutions: 
- Change the summary table from Offset to dataOffset, modifying the description accordingly to describe that there is one offset per channel
- Add a description for Offset and indicate if it is possible to have both Offset and DataOffset present in a file. 

Actually, since dataOffset is channel specific. I am wondering if it should not be movded to measurementList ( and measurementLists). similarly to how detectorGain is encoded. 

Regards, 
Edouard

hs: As discussed during the fnirs conference, i am still interested in joining the maintainer team :)

**Comment by samuelpowell** [comment]
Thanks @Edouard2laire, the proposal in #126 was for the field to be `/nirs(i)/data(j)/dataOffset` but the implementation in #143 ended up with the alternative name in the summary.

The obvious fix here is to modify the summary to be consistent with the body (PR welcome), though I take your point about the location of the field (cf. measurementList) and so let's leave this open for a short period to see if there are any strong views.
