### ISSUE TITLE
Distinction between nominal and real wavelengths measurements

### ISSUE THREAD

**Issue by forihuelaespina** [fNIRS/snirf#20]
Extracted from the Google Docs: https://docs.google.com/document/d/1kLQnFNSXsCAcUNcCPtyTerSwatCOnLcX4fAaZsidCbI/edit

HITACHI ETG family used to make a distinction between "nominal" wavelength e.g. 690nm common to all channels and "real" measurement wavelength e.g. 696.6nm, specific at each channel. Is there any advantage to keep track of both?

**Comment by Horschig** [comment]
If channels refer back to these wavelengths, then it would be easier to combine 'similar' wavelength by referring to the nominal wavelength. This way, the manufacturers define which wavelengths should be in one set and not the user. Alternatively, the user has to arbitrarily define a tolerance until when wavelengths are equal. The real wavelength is, however, necessary to transform the data properly. Therefore, I would be in favor of having both.

**Comment by dboas** [comment]
Qianqian, Ted, Jay and I discussed adding an optional probe.wavelengthLabels field... This just seems to get ugly from my perspective when try to envision how to utilize this as described above.

Instead, it seems like maybe it will be easier if we add a data(0).measurementList(0).wavelengthLabel field which will be a string descriptor of the wavelength. This could be used to store the real wavelength or what ever descriptor the person wants to provide for the wavelength of that measurement channel.

This needs more discussion before we incorporate into the spec
