### ISSUE TITLE
Support for dataTimeSeries types

### ISSUE THREAD

**Issue by forihuelaespina** [fNIRS/snirf#21]
Extracted from the Google Docs: https://docs.google.com/document/d/1kLQnFNSXsCAcUNcCPtyTerSwatCOnLcX4fAaZsidCbI/edit

In the supported data types for “dataTimeSeries”, how are variants of DCS indicated e.g. TD-DCS?

**Comment by fangq** [comment]
these are now supported via the dataType labels

https://github.com/fNIRS/snirf/blob/master/snirf_specification.md#appendix
