### ISSUE TITLE
container for multimodal data

### ISSUE THREAD

**Issue by dboas** [fNIRS/snirf#24]
Hasan Ayaz raised the issue

> One suggestion is related to adding a dedicated multimodal data collection component by adding a new container, this could contain a string list of other biomedical signals (e.g. EEG, ECG, PPG, EMG, EDA, etc.) collected together with fNIRS as well as time synchronization (i.e. time offset between the other time-series and fNIRS origin, and/or other key events) which is needed between these datasets in any case. These could be implemented over existing part (e.g. stim or aux ) but having a dedicated mechanism would be useful going forward.

I believe that this is already covered within the aux container. Am I missing something?

**Comment by fangq** [comment]
close this ticket. if the issue was not correctly addressed in the spec, please feel free to reopen.
