### ISSUE TITLE
Should consider a license for the document, and add a LICENSE.md file

### ISSUE THREAD

**Issue by fangq** [fNIRS/snirf#3]
Possible licenses (permit commercial use) include, but not limited to
- public domain
- CC-BY-SA
- BSD
- Apache 2.0

related documents see
https://help.github.com/articles/licensing-a-repository/
https://en.wikipedia.org/wiki/Creative_Commons_license
https://www.dreamsongs.com/IHE/IHE-50.html

**Comment by dboas** [comment]
To have full impact, it seems to me that people need to be able to repackage source code as they see fit without restrictions. MIT License would permit this. 
The spec itself is not software. So I am not sure what is the appropriate license for that.
Your thoughts?

**Comment by fangq** [comment]
all the above mentioned licenses, including MIT, are permissive licenses, although, some of them are designed for software. The license we are looking for is a free "document license". You can find a few common document (or content) licenses here

https://en.wikipedia.org/wiki/List_of_free_content_licenses
https://choosealicense.com/non-software/

for example, most wikipedia pages are under the CC-BY-SA license; the documentations in the Android are under either Apache 2 or CC license

https://source.android.com/license

MIT, BSD or GNU all have specialized tweaked towards documentation licenses (FreeBSD Documentation license or GFDL).

**Comment by dboas** [comment]
QIanqian, which would you choose and why?
David

**Comment by fangq** [comment]
my preference ranks as public domain >= CC-BY-SA  > Apache 2 > others. 

if you choose CC-BY-SA, any commercial company or academic work claiming to be compliant to SNIRF needs to include your copyright (or anyone who had contributed to the document) in a document (normally README or master document). if you choose public domain, people use it without needing to acknowledge, which is also often used in specifications. I list Apache 2 because it is permissive and has priors as a documentation license. Other forms are either less popular or software oriented.

**Comment by fangq** [comment]
As confirmed by David, the specification is released in the public domain. Added an [Acknowledgement section](https://github.com/fNIRS/snirf/blob/master/snirf_specification.md#acknowledgement) to include the names of the contributors (to be added by David).
