### ISSUE TITLE
Converters for other formats to SNIRF

### ISSUE THREAD

**Issue by rob-luke** [fNIRS/snirf#39]
Thanks for the great initiative.

I would like to convert my existing data (NIRX) to the SNIRF format. Are there any conversion scripts available? I have looked in the fNIRS organisation and can only find SNIRF readers and writers.

Apologies if I have posted this in the wrong location, I was not sure what repository to ask this question in.

**Comment by robquant** [comment]
Hi @rob-luke,

I am the software team lead at NIRx. We are currently working on incorporating support for the SNIRF format in future versions of our recording software. Could you contact me at robert.franke_at_nirx.de so we can learn more about your requirements for a conversion tool?

**Comment by dboas** [comment]
﻿Completely awesome you all are supporting SNIRF. Let us know through https://github.com/fNIRS/snirf if we can help with any aspects of SNIRF

**Comment by fangq** [comment]
@robquant feel free to follow up in this thread if you want to post any updates on the converter development. If your team decide to make any of those converters to be released under an open-source license, feel free to let me know so I can add a submodule link in this repository.

Closing this ticket for now.
