### ISSUE TITLE
Specify data types, endianness and maximum string length

### ISSUE THREAD

**Issue by fangq** [fNIRS/snirf#4]
here is a list of sub-fields and their preferred data types:

## Container type (struct or cell-like data in MATLAB):
- data(idx)
  - data(idx).ml
- stim
- sd
- metaDataTags
- aux

## Floating-point types (double as default - should we also support single-precision?):
- data(idx).d
- data(idx).t
- data(idx).ml.sourcePower
- data(idx).ml.detectorGain
- stim(n).data
- sd.lambda
- sd.lambdaEmission
- sd.srcPos
- sd.detPos
- aux(n).d
- aux(n).t
- timeOffset

## Integer types:
- data(idx).ml.sourceIndex
- data(idx).ml.detectorIndex
- data(idx).ml.wavelengthIndex
- data(idx).ml.dataType
- data(idx).ml.dataTypeIndex

## String types:
- formatVersion
- stim(n).name
- sd.srcLabels
- sd.detLabels
- aux(n).name

**Comment by fangq** [comment]
hi @dboas, upon listing all the subfields in types, I realized that *data(idx).ml* is actually a container type, and has both integer and floating point subfields.

**Comment by fangq** [comment]
just merged the changes I made over the past few weeks, commit 84e689844fd101951c5d1cf807ec7f1248d9738b addressed this issue. closing.

**Comment by jayd1860** [comment]
Hi Qianqian,


I'm on vacation until Nov 21. I will take a look as soon as I'm back and get back to you with what I think.


Jay

________________________________
