### ISSUE TITLE
I have a python library I'd like to contribute

### ISSUE THREAD

**Issue by bbfrederick** [fNIRS/snirf#5]
I have a python library to read and write .snirf files [here](https://github.com/bbfrederick/pysnirf).  Is it best to merge it into this tree, or keep it separate?

**Comment by fangq** [comment]
@bbfrederick, thanks. 

David asked me to help with the SNIRF specification development on github. I just created a fork of your python library in the fNIRS folder. I also sent you an invitation as the contributor to fNIRS/pysnirf. 

My suggested workflow is that we continue to use our own personal fork (like [mine](https://github.com/fangq/snirf)) to develop the software modules, and then, once it is stable, create a pull request and merge those to fNIRS folder. This gives David and others opportunities to review the changes before merging to the public-facing repositories (i.e. those in the fNIRS folder).

let me know if you are able to see the newly created fork. I am closing this ticket for now.

**Comment by dboas** [comment]
@bbfrederick and @fangq , I don't see @bbfrederick 's code in the repository.
@bbfrederick , I think it is best to include your python code in this repository if you are okay with that.

**Comment by bbfrederick** [comment]
Sure thing. Do you want to fork it from my git repository or is there some easy way for me to add it?

Blaise

**Comment by dboas** [comment]
Blaise, I am not sufficiently knowledgeable yet with GitHub. You tell me what is best.
We are still finalizing the spec. This will be done in Feb! After that, your Python code will have to be updated to match the final spec. But maybe it is good to just get your code in the repository now and then updare it once the spec is finalized. What do you think?
David

**Comment by bbfrederick** [comment]
Sounds good to me. I guess I can do a pull request (it will take me a while to figure out how - I too find github a bit mystifying, despite using it).  Then I’ll work I’m becoming compliant with the final spec. 

Blaise

**Comment by fangq** [comment]
@dboas and @bbfrederick, the repository has already been added to the fNIRS github portal, see

https://github.com/fNIRS/pysnirf

Blaise has write access to the repository as well.
