### ISSUE TITLE
Simplify the readme for USERS of the SNIRF specification

### ISSUE THREAD

**Issue by rob-luke** [fNIRS/snirf#62]
A colleague of mine opened the SNIRF specification to understand it better (after my pushing) and had two follow up comments that I thought I would share with you. 1) Do I need to install TortoiseGit? And, 2) I don't use git, so I don't think SNIRF is for me. As such, I suggest the following:

Split the README in to user instructions (friendly with text links), then developer instructions (all the git info you can dream of).

The instructions on how to use TortoiseGit are the second thing you see on the SNIRF landing page. It is almost the most dominant aspect of the README. For new users this may be confusing, as they will wonder if they need his software to use SNIRF, whereas they don't, SNIRF is a specification and the instructions of how to clone a repository are mainly developer focused. If you wish to link to software, the average user just wants to know that Homer, NIRS-Toolbox, MNE, Fieldtrip, etc support it. So maybe it would be better to include a list or table of software that support SNIRF?

I suggest moving the TortoiseGit section down to the bottom of the page under the `How to Participate` section. Or even removing it, its a very specific tool and not particularly widely used, is TortoiseGit something used at BU?

Move all the details about git recursive cloning, submodules, etc to the developer focused section.

I hope this user feedback helps. While your average user won't be implementing SNIRF, this is likely the page they will land when googling the topic. 

If there is general agreement for this change I'll open a PR.

**Comment by dboas** [comment]
I agree that this tortoisegit stuff can be removed because it is a specific tool for git access and not related to SNIRF. I am not sure how it got there.

I agree with moving git detail stuff to a developer focused section

@rob-luke , thanks for taking care of this change. I am sure @fangq will agree with it.

**Comment by rob-luke** [comment]
Great. In that case I will open a PR in the coming days to tidy up the landing page. We can iterate on the details with @fangq once I have a suggestion to comment on.

**Comment by fangq** [comment]
@rob-luke and @dboas, I am fine to remove tortoisegit. it was meant for informative, but ended up as the 2nd link in README. so, no need to emphasize it as much.
