### ISSUE TITLE
Data streaming support

### ISSUE THREAD

**Issue by fangq** [fNIRS/snirf#7]
hi @dboas, I remember Ted mentioned about this in an teleconference previously. Recently, my student Morris Vanegas also brought up this issue. 

I think we should add some sequence numbers in the data structure to allow grouping data chunks into a larger dataset, possibly in the metaDataTags section. DICOM format uses the "Accession Number", although it is a string format.

I can think about something related to this feature, and propose an update.

**Comment by dboas** [comment]
sounds good to me... for instance, we have collected data for 7 days straight... we just had files for every 30 minutes of data with a number incrementing in the filename. Would be good to have that specification in the file structure as well.

**Comment by fangq** [comment]
I added the streaming support in this pull request #11, let me know if it is acceptable.

**Comment by fangq** [comment]
closed after accepting Pull request #11
