### ISSUE TITLE
Meet the GitHub community guidelines

### ISSUE THREAD

**Issue by rob-luke** [fNIRS/snirf#76]
As this is a community orientated project I suggest we update the repository to meet the GitHub community guidelines https://docs.github.com/en/communities Most of this work has already been done by @fangq, but I suggest simply organising it as recommended by GitHub. See https://github.com/fNIRS/snirf/community for our scorecard

This will involve:

- [x] Move the contribution guidelines from the README to contributing.md ([instructions](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors))
- [x] Add issue and pull request templates ([instructions](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates))
- [ ] Add code of conduct ([instructions](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project))

I am happy to chip away at this in those times where I am waiting for my code to run 😉

**Comment by dboas** [comment]
sounds good. Thanks @rob-luke
