### ISSUE TITLE
Add optional coordinate system field to probe

### ISSUE THREAD

**Issue by rob-luke** [fNIRS/snirf#89]
There are a variety of standardised coordinate systems used in fNIRS (this problem also exists in MRI, MEG, EEG). Currently it is difficult to determine the coordinate frame used in different SNIRF files, as you need to reverse engineer it from the optional fields of `landmarklabels` and `landmarkpos`.

Here are some nice references on the different coordinate systems:
* https://www.fieldtriptoolbox.org/faq/coordsys/
* https://mne.tools/dev/auto_tutorials/forward/20_source_alignment.html#understanding-coordinate-frames
* https://bids-specification.readthedocs.io/en/stable/99-appendices/08-coordinate-systems.html 

I propose that we add a new **optional**  field called `/nirs(i)/probe/coordinatesystem`. And specify a recommended list of standard names to encourage interoperability.

For reference, I believe both NIRx and Kernel uses the `MRI` coordinate system (same as freesurfer). I do not know what Homer uses (but I would like to find out please). But I was only able to determine this by trial and error, and can currently not determine this automatically from the SNIRF file alone (e.g. Kernel does not use the optional `landmarklabels`) field.

#### Possible reasons not to include this

It is possible to try and reverse engineer the coordinate frame from the `landmarklabels` and `landmarkpos`. So one might argue this new field is superfluous. But this reverse engineering is difficult, and sometimes you can get it wrong. 

See also https://github.com/mne-tools/mne-python/pull/9929

**Comment by sstucker** [comment]
I do not think this is superfluous! I am also interested in what the vision is/was for the probe coordinate system standardization
