### ISSUE TITLE
Datasets erroneously saved as arrays

### ISSUE THREAD

**Issue by sstucker** [fNIRS/snirf#98]
Lots of implementations (critically, the Homer3/AtlasViewer BUNPC sponsored MATLAB apps) are saving fields that should just be single ints, floats, strings as H5_ARRAY with length 1, ndim 1. 

This is a formatting difference that affects the way such Datasets must be loaded across reader implementations.

[pysnirf2](https://github.com/BUNPC/pysnirf2) invalidates these files. Because this implementation is so widespread, it is worth considering supporting it. I am opposed, just like I am opposed to supporting both fixed and variable length strings... As in #72 the issue has arisen because the default behavior of the HDF5 library differs.

**Comment by rob-luke** [comment]
I am also opposed to supporting this. It would increase the complexity of snirf readers to support both options.

Also from a fundamentals standpoint. These fields should be a single value. And changing the spec to match incorrect implementations would be a long game of whack a mole.

**Comment by dboas** [comment]
we are still early in the Homer implementation of SNIRF. Seems better to fix Homer than change the SNIRF spec.

**Comment by sstucker** [comment]
An example of MATLAB's `h5disp` function's interpretation of the difference:
![image](https://user-images.githubusercontent.com/22327925/149033593-00f59c5f-c8c7-4549-95dd-b879fe862335.png)

Infuriatingly, the HDFView tool we've been using to inspect files glosses over this difference:
![image](https://user-images.githubusercontent.com/22327925/149033635-d1765f06-bbe6-4250-b590-04a228fcdd63.png)

I will open a PR to get this resolved in the spec and make sure sample code to properly save scalars in MATLAB is provided

**Comment by rob-luke** [comment]
I was also mirroring the way that Homer was storing these ints as single length arrays. I have fixed MNE to match the spec rather than Homer in PR https://github.com/mne-tools/mne-nirs/pull/429

Thanks for highlighting these issues @sstucker. The validator is already paying for itself 😄

**Comment by sstucker** [comment]
Check out the code samples that @chrsthur and I are working out: https://github.com/sstucker/snirf/blob/formatting/snirf_specification.md#code-samples

**Comment by sstucker** [comment]
> Oh! Very handy, thanks!

It is possible some are faulty or overengineered... Maybe you have some experience.
